name: ocode-Template
version: '${project.version}'
main: pl.ocode.template.TemplatePlugin
api-version: '1.16'
authors: [author]
description: ocode-Template plugin created by oasiscode.pl
website: https://oasiscode.pl
