name: oCode-AnarchiaValentines
version: '${project.version}'
main: pl.ocode.anarchiavalentines.AnarchiaValentinesPlugin
api-version: '1.18'
authors: [author]
description: oCode-AnarchiaValentines plugin created by oasiscode.pl
website: https://oasiscode.pl
